### ISSUE TITLE
[STORY] Split caikit/TGIS ServingRuntime into three distinct images

### ISSUE THREAD

**Issue by Xaenalt** [opendatahub-io/caikit#11]
From req doc:

**P0: OOTB support Caikit/TGIS**
- 3 separate options - need to doc differences: caikit+tgis (current), caikit, tgis
- Can only be enabled if KServe is enabled

Caikit+TGIS:
- https://github.com/opendatahub-io/caikit-tgis-serving/issues/164

TGIS standalone:
- https://github.com/opendatahub-io/caikit-tgis-serving/issues/134

Caikit:
- https://github.com/opendatahub-io/caikit-tgis-serving/issues/163

**Comment by dtrifiro** [comment]
Progress:
- [x] Caikit standalone image
- [x] sample manifests for kserve `InferenceService` and `ServingRuntime`
- [] Proper `TGIS`/`caikit` containers networking

**Comment by dtrifiro** [comment]
Related to `caikit-standalone` image (without tgis backend):

https://github.com/caikit/caikit-nlp/pull/210

**Comment by dtrifiro** [comment]
PR at https://github.com/opendatahub-io/caikit-tgis-serving/pull/107

**Comment by heyselbi** [comment]
https://github.com/caikit/caikit-nlp/pull/216

**Comment by bdattoma** [comment]
@Xaenalt could you share how to use the 3 options? even if doc is not completed, maybe you could share some instructions internally. Thanks!

**Comment by bdattoma** [comment]
> @bdattoma the idea is to have the options reported here [opendatahub-io/caikit-tgis-serving#121](https://github.com/opendatahub-io/caikit-tgis-serving/issues/121). Feel free to reach out if you need more information. Hopefully I will have a PR ready in the next few hours

okay thank you. I'll wait for your PR :)

**Comment by heyselbi** [comment]
https://github.com/caikit/caikit-nlp/pull/244/

**Comment by dtrifiro** [comment]
@bdattoma it seems that the above issue I linked above does need a few requirements such as the above PR before being ready, so you'll have to wait some more time :sweat_smile:

**Comment by heyselbi** [comment]
Follow up issue on OOTB inclusion of all images in RHODS: https://github.com/opendatahub-io/caikit/issues/17

**Comment by bdattoma** [comment]
@Xaenalt for tracking purposes, could you edit this Issue saying explicitly that the only scenario covered was the Caikit+TGIS? by reading at it it looks like this issue covered also standalone Caikit and standalone TGIS

**Comment by Xaenalt** [comment]
This got deferred to 2.6

**Comment by Xaenalt** [comment]
Additionally, prompt tuning workflow we're pretty close on having a working test for too

**Comment by heyselbi** [comment]
@bdattoma I will convert this issue to story and have separate issues for each image.

**Comment by bdattoma** [comment]
> This got deferred to 2.6. TGIS standalone is ready for use, but won't ship in 2.5 due to management priorities, caikit standalone dockerfile has merged upstream, we just need to build downstream and that's done

thanks for the update @Xaenalt! We will plan QE effort accordingly. 

> @bdattoma I will convert this issue to story and have separate issues for each image.
@heyselbi lgmt, thanks!!

**Comment by heyselbi** [comment]
moved to JIRA
