### ISSUE TITLE
[P0] [SPIKE] Caikit or TGIS update should have no impact on customer

### ISSUE THREAD

**Issue by heyselbi** [opendatahub-io/caikit#12]
From req doc:

Upon update to new version, there should be no change for existing customers (eg. disabled by default)
- [ ] verify what is expected behavior
- [ ] test it
- [ ] write instructions

**Comment by heyselbi** [comment]
Caikit-TGIS image update has been tested with QE (Berto) - image is updated only for new deployments - not current ones.

**Comment by heyselbi** [comment]
Need to define expected behavior.

**Comment by israel-hdez** [comment]
How is this different from opendatahub-io/caikit-tgis-serving#11 ?

**Comment by heyselbi** [comment]
@israel-hdez I believe that one tests the Caikit+TGIS image. This needs to ensure that no impact is with all three images: Caikit+TGIS, Caikit, TGIS.

**Comment by israel-hdez** [comment]
Upgrades that are in-place would be discouraged. If the upgrade is done as suggested [here](https://github.com/opendatahub-io/caikit-tgis-serving/issues/11#issuecomment-1731701003), an upgrade should not have any impact on any model/server that is already deployed. The user would need to create new deployments and gradually move their apps to the new version.

Caikit and TGIS should follow that same recommendation, so I think this ticket should use the same solution as in opendatahub-io/caikit-tgis-serving#11.

**Comment by israel-hdez** [comment]
I will close this issue on the understanding that we may want to follow the upgrade procedure described here: https://github.com/opendatahub-io/caikit-tgis-serving/issues/11#issuecomment-1731701003. Upgrading that way should lead to minimal impact on users.
