### ISSUE TITLE
Define how Caikit/TGIS will be included OOTB in KServe deployment

### ISSUE THREAD

**Issue by heyselbi** [opendatahub-io/caikit#17]
Follow up to issue #11 
A precise mechanism of OOTB inclusion of Caikit and TGIS images need to be defined. This needs to be communicated/consulted with UX and UI teams, and QE should be notified.

Acceptance criteria:
- [x] Meet with PM, UX and UI teams to define inclusion of Caikit and TGIS OOTB
- [x] Notification of QE

**Comment by bdattoma** [comment]
Cannot we re-use the concept of Custom Serving Runtime we already have?

**Comment by heyselbi** [comment]
@bdattoma yess that's how it would be. 
@Xaenalt could you please attach/comment with the SR for combined TGIS+Caikit image?

**Comment by Xaenalt** [comment]
https://github.com/opendatahub-io/odh-dashboard/pull/2113

**Comment by heyselbi** [comment]
Closing this issue as UI and QE are already aware and this is planned to be included in 2.5
