### ISSUE TITLE
[P0] Verify which metrics CAIKit/TGIS produce

### ISSUE THREAD

**Issue by heyselbi** [opendatahub-io/caikit#3]

**Comment by heyselbi** [comment]
@VedantMahabaleshwarkar could you provide more details here? And add necessary labels, complexity etc?

**Comment by VedantMahabaleshwarkar** [comment]
@heyselbi this work will be tracked as a part of the overall metrics investigation. Can we add this issue as a subtask in https://github.com/opendatahub-io/opendatahub-community/issues/70 ?

**Comment by VedantMahabaleshwarkar** [comment]
instructions to enable caikit metrics in Openshift Console : https://github.com/opendatahub-io/opendatahub-community/issues/70

**Comment by VedantMahabaleshwarkar** [comment]
Caikit and tgis metrics have been verified at port 8086 and 3000 respectively in the kserve container. 
Getting the metrics working with the observability stack is not in the scope for this particular ticket and will be tracked in the overall metrics spike for kserve
