### ISSUE TITLE
[P0] Demo with Kserve + Caikit + TGIS + NVIDIA GPUs

### ISSUE THREAD

**Issue by heyselbi** [opendatahub-io/caikit#5]
This demo is based on the upstream components
- Istio
- Knative
- Cert Manager
- Caikit Serving Runtime

**Comment by Xaenalt** [comment]
Testing completed, demo READMEs can be found at https://github.com/Xaenalt/caikit-serving/blob/main/README.md using upstream bits, and https://github.com/Jooho/caikit-serving/tree/downstream-demo/kserve-demo for the downstream bits

**Comment by bdattoma** [comment]
@Xaenalt @Jooho the downstream demo does not exist anymore. Could you pls double check?

**Comment by Jooho** [comment]
@bdattoma  I changed the folder and I sent a PR for it : https://github.com/Xaenalt/caikit-serving/pull/1

**Comment by bdattoma** [comment]
thank u :)
